name: Deploy HTML to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Preparar arquivos para deploy
        run: |
          mkdir output
          cp index.html output/

      - name: Deploy no Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-cicd-bruno99431
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./output
